
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:10.1.0
        resources:
        ports:
        - containerPort: 3000
      
        env:
          - name: GF_AUTH_ANONYMOUS_ENABLED
            valueFrom:
              configMapKeyRef:
                name: grafana-cmap
                key: GF_AUTH_ANONYMOUS_ENABLED

          - name: GF_AUTH_ANONYMOUS_ORG_ROLE
            valueFrom:
              configMapKeyRef:
                name: grafana-cmap
                key: GF_AUTH_ANONYMOUS_ORG_ROLE
          

          - name: GF_AUTH_DISABLE_LOGIN_FORM
            valueFrom:
              configMapKeyRef:
                name: grafana-cmap
                key: GF_AUTH_DISABLE_LOGIN_FORM


          
        volumeMounts:
          - name: grafana-config
            mountPath: /etc/grafana/provisioning/datasources

      volumes:
        - name: grafana-config
          configMap:
            name: grafana-cmap
        
---

apiVersion: v1
kind: Service
metadata:
  name: grafana
spec:
  selector:
    app: grafana
  ports:
    - port: 3003
      targetPort: 3000


---

apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-cmap
data:
  GF_AUTH_ANONYMOUS_ENABLED: "true"
  GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin"
  GF_AUTH_DISABLE_LOGIN_FORM: "true"
   
  dataSources.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus.default.svc.cluster.local:9090
        editable: false
        jsonData:
           httpMethod: POST
           exemplarTraceIdDestinations:
             - name: trace_id
               datasourceUid: tempo   

      - name: Tempo
        type: tempo
        access: proxy
        orgId: 1
        url: http://tempo.default.svc.cluster.local:3200
        basicAuth: false
        isDefault: true
        version: 1
        editable: false
        apiVersion: 1
        uid: tempo
        jsonData:
          httpMethod: GET
          tracesToLogs:
            datasourceUid: 'loki'
          nodeGraph:
            enabled: true

      - name: Loki
        type: loki
        uid: loki
        access: proxy
        orgId: 1
        url: http://loki.default.svc.cluster.local:3100
        basicAuth: false
        isDefault: false
        version: 1
        editable: false
        apiVersion: 1
        jsonData:
          derivedFields:
            -   datasourceUid: tempo
                matcherRegex: \[.+,(.+?),
                name: TraceID
                url: $${__value.raw}

