
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: broker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: broker
  template:
    metadata:
      labels:
        app: broker
    spec:
      enableServiceLinks: false
      containers:
        - name: broker
          image: confluentinc/cp-kafka:7.5.0
        
          ports:
            - containerPort: 29092
            - containerPort: 9092

          env:
          - name: KAFKA_BROKER_ID
            valueFrom:
              configMapKeyRef:
                name: broker-cmap
                key: KAFKA_BROKER_ID

          - name: KAFKA_ZOOKEEPER_CONNECT
            valueFrom:
              configMapKeyRef:
                name: broker-cmap
                key: KAFKA_ZOOKEEPER_CONNECT  

          - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
            valueFrom:
              configMapKeyRef:
                name: broker-cmap
                key: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP

          - name: KAFKA_ADVERTISED_LISTENERS
            valueFrom:
              configMapKeyRef:
                name: broker-cmap
                key: KAFKA_ADVERTISED_LISTENERS     

          - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
            valueFrom:
              configMapKeyRef:
                name: broker-cmap
                key: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
               
            
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: broker-cmap
data:
  KAFKA_BROKER_ID: "1"
  KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
  KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
  KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://broker-svc:29092,PLAINTEXT_HOST://localhost:9092"
  KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"


---

apiVersion: v1
kind: Service
metadata:
  name: broker-svc
spec:
  selector:
    app: broker
  ports:
    - protocol: TCP
      port: 29092
      targetPort: 29092
      name: kafka-internal

      
    - protocol: TCP
      port: 9092
      targetPort: 9092
      name: kafka

