
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
spec:
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
      - name: myapp
        image: prom/prometheus:v2.46.0
      
        ports:
        - containerPort: 9090

        args:
          - --enable-feature=exemplar-storage
          - --config.file=/etc/prometheus/prometheus.yml

        volumeMounts:
          - name: prometheus-config-volume
            mountPath: /etc/prometheus

      volumes:
        - name: prometheus-config-volume
          configMap:
            name: prometheus-cmap
          

---

apiVersion: v1
kind: Service
metadata:
  name: prometheus
spec:
  selector:
    app: prometheus
  ports:
    - port: 9090
      targetPort: 9090



---


apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-cmap
data:
  prometheus.yml: |
    
    global:
      scrape_interval: 2s
      evaluation_interval: 2s

    scrape_configs:
    
      - job_name: 'ApiGateway'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: [ 'ApiGateway.default.svc.cluster.local:3000']  

      - job_name: 'PaymentService'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ['PaymentService.default.svc.cluster.local:8082']



      - job_name: 'OrderService'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: [ 'OrderService.default.svc.cluster.local:8081' ]


      - job_name: 'ProductService'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: [ 'ProductService.default.svc.cluster.local:8080' ]


      - job_name: 'NotifyServices'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: [ 'NotifyServices.default.svc.cluster.local:8087' ]


