
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
      - name: zookeeper
        image: confluentinc/cp-zookeeper:7.5.0

        ports:
        - containerPort: 2181

        env:
        - name: ZOOKEEPER_CLIENT_PORT
          valueFrom:
            configMapKeyRef:
              name: zookeeper-cmap
              key: ZOOKEEPER_CLIENT_PORT  

        - name: ZOOKEEPER_TICK_TIME
          valueFrom:
            configMapKeyRef:
              name: zookeeper-cmap
              key: ZOOKEEPER_TICK_TIME

---

apiVersion: v1
kind: Service
metadata:
  name: zookeeper
spec:
  selector:
    app: zookeeper
  ports:
    - port: 2181
      targetPort: 2181



---

apiVersion: v1
kind: ConfigMap
metadata:
  name: zookeeper-cmap
data:
  ZOOKEEPER_CLIENT_PORT: "2181"
  ZOOKEEPER_TICK_TIME: "2000"


