---

apiVersion: v1
kind: ConfigMap
metadata:
  name: eureka-cmap
data:
  eureka-service-address: "http://eureka-0.eureka:8761/eureka"


---

apiVersion: v1
kind: ConfigMap
metadata:
  name: config-cmap
data:
  config-server-url: "config-server-svc"


---

apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-cmap
data:
  hostname: "mysql-0.mysql"

  

