
server:
  port: 8082

spring:
  application:
    name: PaymentService
  datasource:
    url: "jdbc:mysql://${DB_HOST:localhost}:3306/paymentdb"
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update

  config:
    import: "configserver:${CONFIG_SERVER_URI:http://localhost:9296/}"

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-biqonisiomf7typl.us.auth0.com/


