server:
  port: 9296

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/BasantaNembang/u-microservice-config
          clone-on-start: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    registry-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUEREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
