
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway-app
  template:
    metadata:
      labels:
        app: api-gateway-app
    spec:
      
      containers:
      - name: api-gateway-app
        image: basantanembang10/apigateway:latest
        ports:
        - containerPort: 3000
        imagePullPolicy: Always
        
        env:
          - name: CONFIG_SERVER_URI
            valueFrom:
              configMapKeyRef:
                name: config-cmap
                key: config_server_uri
             
        
          
          - name: LOKI_URL
            valueFrom:
              configMapKeyRef:
                name: common-config
                key: LOKI_URL

          - name: MANAGEMENT_ZIPKIN_TRACING_ENDPOINT
            valueFrom:
              configMapKeyRef:
                name: common-config
                key: MANAGEMENT_ZIPKIN_TRACING_ENDPOINT
          
          # - name: REDIRECT_URI
          #   valueFrom:
          #     configMapKeyRef:
          #       name: redirect-url-cmap
          #       key: REDIRECT_URI 
       




---

apiVersion: v1
kind: Service
metadata:
  name: api-gateway-svc
spec:
  type: LoadBalancer
  selector:
    app: api-gateway-app
  ports:
  - port: 80
    targetPort: 3000




#LET`S IMPLEMENT INGRESS-SERVICE`
# ---


# apiVersion: v1
# kind: Service
# metadata:
#   name: api-gateway-svc
# spec:
#   selector:
#     app: api-gateway-app
#   ports:
#   - port: 80
#     targetPort: 3000


# ---

# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: api-gateway-ingress

    
# spec:
#   ingressClassName: nginx
#   rules:
#   - host: api-gateway-local.com
#     http:
#       paths:
#       - pathType: Prefix
#         path: "/"
#         backend:
#           service:
#             name: api-gateway-svc
#             port: 
#               number: 80



