
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notify-service-app
spec:
  selector:
    matchLabels:
      app: notify-service-app
  template:
    metadata:
      labels:
        app: notify-service-app
    spec:
      containers:
      - name: notify-service-app
        image: basantanembang10/notifyservice:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8087

        env:
          - name: LOKI_URL
            valueFrom:
              configMapKeyRef:
                name: common-config
                key: LOKI_URL

          - name: MANAGEMENT_ZIPKIN_TRACING_ENDPOINT
            valueFrom:
              configMapKeyRef:
                name: common-config
                key: MANAGEMENT_ZIPKIN_TRACING_ENDPOINT  

          - name: BOOTSTRAP_SERVER
            valueFrom:
              configMapKeyRef:
                name: common-config
                key: BOOTSTRAP_SERVER         
       

          - name: SCHEMA_REGISTRY_URL
            valueFrom:
              configMapKeyRef:
                name: notify-service-cmap
                key: SCHEMA_REGISTRY_URL


---

apiVersion: v1
kind: Service
metadata:
  name: notify-service-svc
spec:
  selector:
    app: notify-service-app
  ports:
  - port: 80
    targetPort: 8087


---

apiVersion: v1
kind: ConfigMap
metadata:
  name: notify-service-cmap
data:
  SCHEMA_REGISTRY_URL: "http://schema-registry-svc:8085"
