


apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service-app
  template:
    metadata:
      labels:
        app: order-service-app
    spec:
      containers:
      - name: order-service-app
        image: basantanembang10/orderservice:latest
        ports:
        - containerPort: 8081

        env:
          - name: CONFIG_SERVER_URI
            valueFrom:
              configMapKeyRef:
                name: config-cmap
                key: config_server_uri
             
         
          
          - name: LOKI_URL
            valueFrom:
              configMapKeyRef:
                name: common-config
                key: LOKI_URL

          - name: MANAGEMENT_ZIPKIN_TRACING_ENDPOINT
            valueFrom:
              configMapKeyRef:
                name: common-config
                key: MANAGEMENT_ZIPKIN_TRACING_ENDPOINT  

          - name: SPRING_KAFKA_BOOTSTRAP-SERVERS
            valueFrom:
              configMapKeyRef:
                name: common-config
                key: SPRING_KAFKA_BOOTSTRAP-SERVERS         
       

          - name: SPRING.KAFKA.PRODUCER.PROPERTIES.SCHEMA.REGISTRY.URL
            valueFrom:
              configMapKeyRef:
                name: order-service-cmap
                key: SPRING.KAFKA.PRODUCER.PROPERTIES.SCHEMA.REGISTRY.URL      

   
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                name: mysql-cmap
                key: hostname               
      
        # readinessProbe:
        #   httpGet:
        #     path: /actuator/health
        #     port: 8081
        #   initialDelaySeconds: 65
        #   periodSeconds: 5
        #   failureThreshold: 3
        #   successThreshold: 1    

          
---

apiVersion: v1
kind: Service
metadata:
  name: order-service-svc
spec:
  selector:
    app: order-service-app
  ports:
  - port: 80 
    targetPort: 8081


---

apiVersion: v1
kind: ConfigMap
metadata:
  name: order-service-cmap
data:
  SPRING.KAFKA.PRODUCER.PROPERTIES.SCHEMA.REGISTRY.URL: "http://schema-registry.default.svc.cluster.local:8085"

