
spring:
  application:
    name: ApiGateway

  redis:
    host: redis
    port: 6379
  # profiles:
  #   active: dev

  config:
    import: "optional:configserver:${CONFIG_SERVER_URI:http://localhost:9296/}"
  cloud:
    config:
      uri: http://config-server-svc
      fail-fast: true
      retry:
        initial-interval: 2000  # 2s
        max-attempts: 10
        max-interval: 10000
        multiplier: 1.5

    gateway:
      default-filters:
        - TokenRelay
      routes:
        - id: ProductService
          uri: http://product-service-svc
          predicates:
            - Path=/product/**
          filters:
            - name: CircuitBreaker
              args:
                name: ProductService
                fallbackUri: forward:/productServiceFallback
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
        - id: PaymentService
          uri: http://payment-service-svc
          predicates:
            - Path=/payment/**
          filters:
            - name: CircuitBreaker
              args:
                name: PaymentService
                fallbackUri: forward:/paymentServiceFallback
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
        - id: OrderService
          uri: http://order-service-svc
          predicates:
            - Path=/order/**
          filters:
            - name: CircuitBreaker
              args:
                name: OrderService
                fallbackUri: forward:/orderServiceFallback
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20

  security:
    oauth2:
      client:
        registration:
          auth0:
            scope: openid, profile, email, offline_access
            authorization-grant-type: authorization_code
            #redirect-uri: "{baseUrl}/login/oauth2/code/auth0"
            #redirect-uri: "${REDIRECT_URI:http://localhost:3000}/login/oauth2/code/auth0"
            redirect-uri: "{baseUrl}/login/oauth2/code/auth0"
            client-id: 2WSuELXOTRX9N2IaLh0SyPW3x1SRjFap
            client-secret: qGaBjWRGHVQJAOWffvg8w-lsn5t4DLl3qdpK8gAWLttI2qnaiXXC11hdlLqEOkd0
        provider:
          auth0:
            issuer-uri: https://dev-biqonisiomf7typl.us.auth0.com/
            jwk-set-uri: https://dev-biqonisiomf7typl.us.auth0.com/.well-known/jwks.json
      resourceserver:
        jwt:
          issuer-uri: https://dev-biqonisiomf7typl.us.auth0.com/

auth0:
  audience: https://dev-biqonisiomf7typl.us.auth0.com/api/v2/

server:
  port: 3000
  address: 0.0.0.0


#   address: 0.0.0.0 #for k8s


